### ISSUE TITLE
Move hard-coded text to locales/en.json

### ISSUE THREAD

**Issue by gkatrakazas** [wwWallet/wallet-frontend#116]
In this issue, we intend to move all hard-coded text content from js files to the locales/en.json file. This action will enhance code organization and maintainability by centralizing text content.

Related pr and usefull links from: https://github.com/wwWallet/wallet-frontend/pull/117

_See: https://react.i18next.com/latest/trans-component#using-with-react-components
and: https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0_

**Comment by emlun** [comment]
I would also suggest an approach I've seen in the Syncthing project, of simply using the [original English text](https://github.com/syncthing/syncthing/blob/439c6c5b7c64eb8f06d2cd4d8f66e27d0e277d2d/gui/default/assets/lang/lang-el.json#L2) as the [translation key](https://github.com/syncthing/syncthing/blob/439c6c5b7c64eb8f06d2cd4d8f66e27d0e277d2d/gui/default/syncthing/device/editDeviceModalView.html#L50) in most cases. This way you can just type `t('Failed to create user account, username already exists')` as a first step, and don't need to break your flow to add a `"usernameExistsError"` key to the translation file. Or even `<Trans>Failed to create user account, username already exists</Trans>`, so you don't even need to prepare the `const { t } = useTranslation();` statement either.

This works best for full sentences or text that is otherwise unlikely to appear in more than one place. It doesn't work as well for single-word labels or other short phrases that might appear in multiple places in different contexts, where conjugations or grammatical gender might make the translation wrong depending on context. See [here](https://github.com/syncthing/syncthing/pull/9192#issue-1977819192) for a few examples.

There are some suggestions [here](https://www.i18next.com/how-to/extracting-translations) for tools for extracting translation keys from the app sources into the translation files. I've not tried any of them myself and don't know how reliable they are.

**Comment by gkatrakazas** [comment]
Looks like a nice approach. I'm also going to investigate the best approach. Additionally, I'd like to mention that translation of the text is not a priority at the moment. We'll probably keep it only in English, but we want to remain flexible for the future and maintain a better structure for the project's text.

**Comment by gkatrakazas** [comment]
Deciding whether to use English text as translation keys in this project can be quite confusing. On one hand, it simplifies the development process, and the context within the code is clearer. Regarding the updates in the key-text, I have found a library that probably works but i dont have test as much i want. On the other hand, this method can be problematic for phrases that are reused in different contexts, as you mentioned earlier. Also, it often leads to bulkier translation files (if we use it in the future), which can be challenging to manage.

I am not sure which is the best practice for our project moving forward.

What do you think?

**Comment by emlun** [comment]
I think both approaches have their advantages, as you point out. I think a hybrid approach is probably best (see https://github.com/syncthing/syncthing/pull/9192#issuecomment-1797977848): use the English text as the translation key by default, and explicit translation keys for texts that are likely to be context-dependent (such as short button labels and similar). I don't think file size is much of a concern; the file will still have the same number of keys, just slightly longer or shorter.

But if we need to pick just one approach, I would err on the side of using explicit translation keys everywhere, as we do currently.
